<?php
/**
 * Config reader.
 *
 * Single source of truth for site/profile/URL config inside the plugin. It does
 * NOT parse YAML at runtime (anti-pattern per PRD-005 CP51). Instead it loads a
 * deployed JSON **config bundle** — the serialised form of the same files the
 * Python pipeline reads:
 *
 *   - config/sites/*.yaml
 *   - config/content_profiles/*.yaml
 *   - config/url_structures.yaml
 *   - config/site_content_entitlements.yaml
 *   - config/artefacts.yaml
 *   - config/staging_qa_matrix.yaml
 *   - config/network_consumer.yaml
 *
 * The bundle is generated by a build step (separate checkpoint) and deployed
 * with the plugin. This keeps the plugin's source of truth identical to the
 * pipeline while avoiding a YAML parser dependency and per-request parsing.
 *
 * Expected bundle shape (JSON):
 * {
 *   "version": "2026-06-16T01:00:00Z" | "<git-sha>",
 *   "generated_at": "<iso8601>",
 *   "sites":            { "<site_id>": { ...site config... }, ... },
 *   "content_profiles": { "<profile_name>": { ...profile... }, ... },
 *   "url_structures":   { ... },
 *   "entitlements":     { ... },
 *   "artefacts":        { ... }
 * }
 *
 * `content_profiles` is keyed by profile NAME (the YAML basename without
 * extension, e.g. "loupe_sites", "ringspo"); each site config's
 * `content_profile` value (a path like
 * "config/content_profiles/loupe_sites.yaml") resolves to that key.
 *
 * @package LoupeDiamondNetwork
 * @since   0.1.0
 */

if (!defined('ABSPATH')) {
    exit;
}

final class LDN_Config {

    /**
     * Transient key for the parsed bundle.
     */
    const TRANSIENT_KEY = 'ldn_config_bundle';

    /**
     * Transient TTL (seconds). Bundle changes only on deploy, so this can be
     * long; it is also invalidated whenever the bundle file mtime changes.
     */
    const TRANSIENT_TTL = 12 * HOUR_IN_SECONDS;

    /**
     * Canonical shape -> S3 slug map. Mirrors shared/utils.py SHAPE_S3_SLUG_MAP
     * exactly. Keys are lowercased shape names.
     *
     * @var array<string, string>
     */
    const SHAPE_S3_SLUG_MAP = array(
        'asscher'           => 'asscher-cut',
        'cushion'           => 'cushion-cut',
        'cushion elongated' => 'cushion-cut',
        'emerald'           => 'emerald-cut',
        'princess'          => 'princess-cut',
    );

    /**
     * Page level (hyphenated, S3/entitlement form) → `page_structure` key
     * (underscored, content-profile form). Mirrors the dual naming noted in
     * site_content_entitlements.yaml.
     *
     * @var array<string, string>
     */
    const PAGE_LEVEL_TO_STRUCTURE_KEY = array(
        'shape'        => 'individual_shape',
        'all-shapes'   => 'all_shapes',
        'diamond-type' => 'diamond_type',
        'top-level'    => 'top_level',
        'calculator'   => 'calculator',
    );

    /**
     * Singleton instance.
     *
     * @var LDN_Config|null
     */
    private static $instance = null;

    /**
     * In-memory copy of the parsed bundle for this request.
     *
     * @var array|null
     */
    private $bundle = null;

    /**
     * Get the singleton instance.
     *
     * @return LDN_Config
     */
    public static function instance() {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Private constructor for singleton.
     */
    private function __construct() {}

    // =========================================================================
    // Bundle loading
    // =========================================================================

    /**
     * Absolute path to the deployed config bundle.
     *
     * Filterable so deployments can point at a shared location outside the
     * plugin directory.
     *
     * @return string
     */
    public function bundle_path() {
        $default = LDN_PLUGIN_DIR . 'data/config-bundle.json';
        return (string) apply_filters('ldn_config_bundle_path', $default);
    }

    /**
     * Load and cache the config bundle.
     *
     * Returns an empty (but well-formed) structure if the bundle is missing or
     * invalid, logging the reason. Callers can always rely on the top-level
     * keys existing.
     *
     * @return array
     */
    public function get_bundle() {
        if ($this->bundle !== null) {
            return $this->bundle;
        }

        $path = $this->bundle_path();
        $mtime = is_readable($path) ? (int) @filemtime($path) : 0;

        $cached = get_transient(self::TRANSIENT_KEY);
        if (is_array($cached) && isset($cached['_mtime']) && $cached['_mtime'] === $mtime && $mtime > 0) {
            $this->bundle = $cached;
            return $this->bundle;
        }

        $this->bundle = $this->read_bundle_file($path, $mtime);
        set_transient(self::TRANSIENT_KEY, $this->bundle, self::TRANSIENT_TTL);

        return $this->bundle;
    }

    /**
     * Read and decode the bundle file from disk.
     *
     * @param string $path  Absolute path to the bundle.
     * @param int    $mtime File mtime (stamped into the result for cache keying).
     * @return array
     */
    private function read_bundle_file($path, $mtime) {
        $empty = $this->empty_bundle($mtime);

        if (!is_readable($path)) {
            $this->log("config bundle not found at {$path}; using empty config");
            return $empty;
        }

        $raw = file_get_contents($path);
        if ($raw === false || $raw === '') {
            $this->log("config bundle at {$path} is empty or unreadable");
            return $empty;
        }

        $decoded = json_decode($raw, true);
        if (!is_array($decoded)) {
            $this->log("config bundle at {$path} is not valid JSON: " . json_last_error_msg());
            return $empty;
        }

        return array_merge($empty, $decoded, array('_mtime' => $mtime));
    }

    /**
     * Well-formed empty bundle so accessors never hit undefined keys.
     *
     * @param int $mtime
     * @return array
     */
    private function empty_bundle($mtime = 0) {
        return array(
            '_mtime'           => $mtime,
            'version'          => null,
            'generated_at'     => null,
            'sites'            => array(),
            'content_profiles' => array(),
            'url_structures'   => array(),
            'entitlements'     => array(),
            'artefacts'        => array(),
            'network_consumer' => array(),
            'ad_slots'         => array(),
        );
    }

    /**
     * Clear cached config (call on deploy / bundle refresh).
     *
     * @return void
     */
    public function flush() {
        $this->bundle = null;
        delete_transient(self::TRANSIENT_KEY);
    }

    // =========================================================================
    // Site accessors
    // =========================================================================

    /**
     * All site configs, indexed by site_id.
     *
     * @return array<string, array>
     */
    public function get_all_sites() {
        $bundle = $this->get_bundle();
        return is_array($bundle['sites']) ? $bundle['sites'] : array();
    }

    /**
     * One site config by site_id.
     *
     * @param string $site_id
     * @return array|null Null when unknown.
     */
    public function get_site($site_id) {
        $sites = $this->get_all_sites();
        return isset($sites[$site_id]) && is_array($sites[$site_id]) ? $sites[$site_id] : null;
    }

    /**
     * Raw url_structures bundle section.
     *
     * @return array
     */
    public function get_url_structures() {
        $bundle = $this->get_bundle();
        return is_array($bundle['url_structures']) ? $bundle['url_structures'] : array();
    }

    /**
     * Localised URL segments per site → country (non-English only).
     *
     * Built by `shared/urls_i18n.py` into the config bundle so C4.5 and this
     * plugin resolve a Japanese path from the same values. English countries
     * are omitted: their URLs come from `url_structures.yaml`.
     *
     * @return array<string, array<string, array>>
     */
    public function get_url_locales() {
        $bundle = $this->get_bundle();
        return isset($bundle['url_locales']) && is_array($bundle['url_locales'])
            ? $bundle['url_locales']
            : array();
    }

    /**
     * Localised path segments for one site × country, or empty for English.
     *
     * @param string $site_id
     * @param string $country Country code (e.g. 'jp').
     * @return array{path_diamond_prices?:string,path_prices?:string,type_natural?:string,type_lab?:string,carat_suffix?:string,locale?:string,shapes?:array<string,string>}
     */
    public function url_locale_segments($site_id, $country) {
        $all = $this->get_url_locales();
        if (!isset($all[$site_id]) || !is_array($all[$site_id])) {
            return array();
        }
        $per_country = $all[$site_id];
        $code = strtolower(trim((string) $country));
        if (isset($per_country[$code]) && is_array($per_country[$code])) {
            return $per_country[$code];
        }
        if (isset($per_country[$country]) && is_array($per_country[$country])) {
            return $per_country[$country];
        }
        return array();
    }

    /**
     * Apply C4.5's path-segment substitutions to one url-structure block.
     *
     * `diamond-prices` is replaced when present; otherwise a trailing `/prices`
     * hub is. Type slugs and `carat_format` become the locale's. Shape slugs
     * stay on the `shapes` map, not in the pattern.
     *
     * @param array $structure
     * @param array $segments From url_locale_segments().
     * @return array
     */
    public function localise_url_structure(array $structure, array $segments) {
        if ($segments === array()) {
            return $structure;
        }
        $out = $structure;
        $path_hub = isset($segments['path_diamond_prices'])
            ? (string) $segments['path_diamond_prices'] : '';
        $path_prices = isset($segments['path_prices'])
            ? (string) $segments['path_prices'] : '';
        foreach ($out as $key => $value) {
            if (!is_string($value)) {
                continue;
            }
            if ($path_hub !== '' && strpos($value, 'diamond-prices') !== false) {
                $out[$key] = str_replace('diamond-prices', $path_hub, $value);
            } elseif (
                $path_prices !== ''
                && (strpos($value, '/prices/') !== false || substr($value, -7) === '/prices')
            ) {
                $out[$key] = str_replace('prices', $path_prices, $value);
            }
        }
        if (!empty($segments['type_natural'])) {
            $out['type_natural'] = (string) $segments['type_natural'];
        }
        if (!empty($segments['type_lab'])) {
            $out['type_lab'] = (string) $segments['type_lab'];
        }
        if (!empty($segments['carat_suffix'])) {
            $out['carat_format'] = '{value}-' . $segments['carat_suffix'];
        }
        return $out;
    }

    /**
     * url-structure for a public path in one country.
     *
     * English countries (and unknown ones) get the yaml block unchanged.
     * Non-English countries get the same substitutions C4.5 applied.
     *
     * @param string      $site_id
     * @param string|null $country
     * @return array|null
     */
    public function url_structure_for($site_id, $country = null) {
        $structure = $this->get_url_structure($site_id);
        if (!is_array($structure)) {
            return $structure;
        }
        if ($country === null || $country === '') {
            return $structure;
        }
        $segments = $this->url_locale_segments($site_id, $country);
        if ($segments === array()) {
            return $structure;
        }
        return $this->localise_url_structure($structure, $segments);
    }

    /**
     * Normalise an install mount to `/` or `/nz/`.
     *
     * @param string $path
     * @return string
     */
    public static function normalise_mount_path($path) {
        $trim = trim((string) $path, '/');
        return $trim === '' ? '/' : '/' . strtolower($trim) . '/';
    }

    /**
     * Path this WordPress install is mounted at (`/` or `/nz/`).
     *
     * Overridable via `ldn_install_mount_path` so tests and the preview harness
     * do not have to fake `home_url()`. Not inferred from `is_multisite()`.
     *
     * @return string
     */
    public function install_mount_path() {
        if (function_exists('apply_filters')) {
            $filtered = apply_filters('ldn_install_mount_path', null);
            if (is_string($filtered) && $filtered !== '') {
                return self::normalise_mount_path($filtered);
            }
        }
        if (function_exists('home_url')) {
            $path = parse_url(home_url('/'), PHP_URL_PATH);
            if (is_string($path) && $path !== '') {
                return self::normalise_mount_path($path);
            }
        }
        return '/';
    }

    /**
     * Country codes declared on a site, lowercased.
     *
     * @param string $site_id
     * @return string[]
     */
    public function site_country_codes($site_id) {
        $site = $this->get_site($site_id);
        if (!is_array($site) || empty($site['countries']) || !is_array($site['countries'])) {
            return array();
        }
        $codes = array();
        foreach ($site['countries'] as $entry) {
            if (is_array($entry) && !empty($entry['code'])) {
                $codes[] = strtolower((string) $entry['code']);
            } elseif (is_string($entry) && $entry !== '') {
                $codes[] = strtolower($entry);
            }
        }
        return $codes;
    }

    /**
     * Country this install serves when the mount path *is* a declared country.
     *
     * `/` and `/blog/` return null: the former is the network root, the latter
     * is a subdirectory that is not a country and must not be stripped.
     *
     * @param string      $site_id
     * @param string|null $mount
     * @return string|null
     */
    public function mount_country($site_id, $mount = null) {
        $mount = $mount !== null
            ? self::normalise_mount_path($mount)
            : $this->install_mount_path();
        $seg = trim($mount, '/');
        if ($seg === '') {
            return null;
        }
        $known = $this->site_country_codes($site_id);
        return in_array($seg, $known, true) ? $seg : null;
    }

    /**
     * Enabled countries this install should register rules for.
     *
     * A country subsite registers only itself. The root (and any mount that is
     * not a declared country) keeps today's "every enabled country" set, so
     * Ringspo.com/uk/… keeps working until those countries move off the root.
     *
     * @param string      $site_id
     * @param string[]    $enabled
     * @param string|null $mount
     * @return string[]
     */
    public function countries_for_install($site_id, array $enabled, $mount = null) {
        $mine = $this->mount_country($site_id, $mount);
        if ($mine === null) {
            return array_values($enabled);
        }
        $enabled = array_map('strtolower', $enabled);
        return in_array($mine, $enabled, true) ? array($mine) : array();
    }

    /**
     * Public url-structure pattern → the install-relative pattern WP matches.
     *
     * `/{country}/diamond-prices` + country `nz` + mount `/nz/` → `/diamond-prices`.
     * Same pattern on mount `/` is unchanged. A mount that is not this country
     * is left unchanged (the caller should not compile that pair).
     *
     * @param string      $pattern
     * @param string      $country
     * @param string|null $mount
     * @return string Empty string when the public path *is* the mount (bare `/{country}`).
     */
    public function install_relative_pattern($pattern, $country, $mount = null) {
        $mount = $mount !== null
            ? self::normalise_mount_path($mount)
            : $this->install_mount_path();
        $country = strtolower((string) $country);
        if ($mount === '/' || trim($mount, '/') !== $country) {
            return $pattern;
        }
        $parts = array_values(array_filter(explode('/', trim((string) $pattern, '/')), 'strlen'));
        if ($parts === array()) {
            return $pattern;
        }
        $first = strtolower((string) $parts[0]);
        if ($first === '{country}' || $first === $country) {
            array_shift($parts);
        }
        return $parts === array() ? '' : '/' . implode('/', $parts);
    }

    /**
     * Public URL path → the remainder to pass to `home_url()`, so a `/nz/`
     * install does not emit `/nz/nz/…`.
     *
     * @param string      $public_path
     * @param string|null $mount
     * @return string
     */
    public function path_relative_to_mount($public_path, $mount = null) {
        $mount = $mount !== null
            ? self::normalise_mount_path($mount)
            : $this->install_mount_path();
        $public = '/' . trim((string) $public_path, '/');
        if ($public === '/') {
            return '/';
        }
        if ($mount === '/') {
            return $public;
        }
        $prefix = rtrim($mount, '/');
        if ($public === $prefix) {
            return '/';
        }
        if (strpos($public . '/', $prefix . '/') === 0) {
            $rest = substr($public, strlen($prefix));
            return $rest === '' ? '/' : $rest;
        }
        return $public;
    }

    /**
     * Entitlements bundle section.
     *
     * @return array
     */
    public function get_entitlements() {
        $bundle = $this->get_bundle();
        return is_array($bundle['entitlements']) ? $bundle['entitlements'] : array();
    }

    /**
     * Staging QA matrix (shape combos, preset groups, country cap).
     *
     * @return array
     */
    public function get_staging_qa_matrix() {
        $bundle = $this->get_bundle();
        return isset($bundle['staging_qa_matrix']) && is_array($bundle['staging_qa_matrix'])
            ? $bundle['staging_qa_matrix']
            : array();
    }

    /**
     * Public HTTPS URL for network-rollout.json (from config/network_consumer.yaml).
     *
     * @return string Empty when the bundle omits rollout.url.
     */
    public function get_rollout_url() {
        $bundle = $this->get_bundle();
        $consumer = isset($bundle['network_consumer']) && is_array($bundle['network_consumer'])
            ? $bundle['network_consumer']
            : array();
        $rollout = isset($consumer['rollout']) && is_array($consumer['rollout'])
            ? $consumer['rollout']
            : array();
        $url = isset($rollout['url']) ? trim((string) $rollout['url']) : '';
        return $url;
    }

    /**
     * network_consumer.yaml slice from the bundle.
     *
     * @return array
     */
    public function network_consumer() {
        $bundle = $this->get_bundle();
        return isset($bundle['network_consumer']) && is_array($bundle['network_consumer'])
            ? $bundle['network_consumer']
            : array();
    }

    /**
     * Combined sitemap index path (price + size child sitemaps).
     *
     * @return string
     */
    public function network_sitemap_index_path() {
        $consumer = $this->network_consumer();
        $path = isset($consumer['network_sitemap_index'])
            ? trim((string) $consumer['network_sitemap_index'])
            : '/sitemaps/network.xml';
        return $path !== '' ? $path : '/sitemaps/network.xml';
    }

    /**
     * Public HTTPS URL for ads.json (network_consumer.ads.manifest_url).
     *
     * @return string
     */
    public function ads_manifest_url() {
        $consumer = $this->network_consumer();
        $ads = isset($consumer['ads']) && is_array($consumer['ads']) ? $consumer['ads'] : array();
        return isset($ads['manifest_url']) ? trim((string) $ads['manifest_url']) : '';
    }

    /**
     * Hub REST base for ad tracking (network_consumer.ads.track_base_url).
     *
     * @return string
     */
    public function ads_track_base_url() {
        $consumer = $this->network_consumer();
        $ads = isset($consumer['ads']) && is_array($consumer['ads']) ? $consumer['ads'] : array();
        return isset($ads['track_base_url']) ? trim((string) $ads['track_base_url']) : '';
    }

    /**
     * ad_slots.yaml slice from the bundle.
     *
     * @return array
     */
    public function ad_slots_config() {
        $bundle = $this->get_bundle();
        return isset($bundle['ad_slots']) && is_array($bundle['ad_slots'])
            ? $bundle['ad_slots']
            : array();
    }

    /**
     * @param string $layout_slot_id
     * @return array<string, mixed>|null
     */
    public function get_layout_slot_definition($layout_slot_id) {
        $config = $this->ad_slots_config();
        $slots = isset($config['layout_slots']) && is_array($config['layout_slots'])
            ? $config['layout_slots']
            : array();
        if (!isset($slots[$layout_slot_id]) || !is_array($slots[$layout_slot_id])) {
            return null;
        }
        return $slots[$layout_slot_id];
    }

    /**
     * @param string $layout_slot_id
     * @param string $page_level
     * @return array{mode: string, section_id?: string}|null
     */
    public function get_layout_slot_placement($layout_slot_id, $page_level) {
        $def = $this->get_layout_slot_definition($layout_slot_id);
        if ($def === null || !isset($def['placement']) || !is_array($def['placement'])) {
            return null;
        }
        $placement = $def['placement'];
        if (isset($placement['by_page_level'][$page_level]) && is_array($placement['by_page_level'][$page_level])) {
            return $placement['by_page_level'][$page_level];
        }
        if (isset($placement['default']) && is_array($placement['default'])) {
            return $placement['default'];
        }
        return null;
    }

    /**
     * @param string $image_size
     * @return array{width: int, height: int, css_class: string}
     */
    public function get_ad_image_dimensions($image_size) {
        $config = $this->ad_slots_config();
        $sizes = isset($config['image_sizes']) && is_array($config['image_sizes'])
            ? $config['image_sizes']
            : array();
        if (!isset($sizes[$image_size]) || !is_array($sizes[$image_size])) {
            return array(
                'width' => 728,
                'height' => 90,
                'css_class' => 'ldn-ad--horizontal',
            );
        }
        $row = $sizes[$image_size];
        return array(
            'width' => isset($row['width']) ? (int) $row['width'] : 728,
            'height' => isset($row['height']) ? (int) $row['height'] : 90,
            'css_class' => isset($row['css_class']) ? (string) $row['css_class'] : 'ldn-ad--horizontal',
        );
    }

    /**
     * Price-module XML sitemap path for a site (from url_structures or derived).
     *
     * @param string $site_id
     * @return string|null
     */
    public function price_sitemap_path($site_id) {
        $structure = $this->get_url_structure($site_id);
        if (!is_array($structure)) {
            return null;
        }
        if (!empty($structure['price_level_sitemap'])) {
            return (string) $structure['price_level_sitemap'];
        }
        if (!empty($structure['level_1'])) {
            return rtrim((string) $structure['level_1'], '/') . '/sitemap.xml';
        }
        return '/diamond-prices/sitemap.xml';
    }

    /**
     * Size-module XML sitemap path for a site.
     *
     * @param string $site_id
     * @return string|null
     */
    public function size_sitemap_path($site_id) {
        $structure = $this->get_url_structure($site_id);
        if (!is_array($structure) || empty($structure['size_level_sitemap'])) {
            return null;
        }
        return (string) $structure['size_level_sitemap'];
    }

    // =========================================================================
    // Content profile resolution (mirrors shared.config.profiles.resolve_content_profile)
    // =========================================================================

    /**
     * Resolve a site's content profile.
     *
     * Reads the site config's `content_profile` value (a path or bare name) and
     * returns the matching entry from the bundle's `content_profiles` map.
     * Template profiles (e.g. loupe_sites) are stored once and shared by every
     * site whose `content_profile` points at them.
     *
     * @param string $site_id
     * @return array|null Null when the site or its profile is unknown.
     */
    public function get_content_profile($site_id) {
        $site = $this->get_site($site_id);
        if ($site === null || empty($site['content_profile'])) {
            return null;
        }

        $name = $this->profile_name_from_ref($site['content_profile']);
        $bundle = $this->get_bundle();
        $profiles = is_array($bundle['content_profiles']) ? $bundle['content_profiles'] : array();

        return isset($profiles[$name]) && is_array($profiles[$name]) ? $profiles[$name] : null;
    }

    /**
     * Merged `file_naming` block for a site's content profile.
     *
     * Used by the S3 key resolver (CP51_03) to build artefact filenames without
     * hardcoding. Returns an empty array when the profile defines none.
     *
     * @param string $site_id
     * @return array
     */
    public function get_file_naming($site_id) {
        $profile = $this->get_content_profile($site_id);
        if ($profile === null || empty($profile['file_naming']) || !is_array($profile['file_naming'])) {
            return array();
        }
        return $profile['file_naming'];
    }

    /**
     * Site IDs that resolve to a given content profile name.
     *
     * Inverts the site -> profile mapping so callers can answer "which sites use
     * the loupe_sites template?" without re-reading `_applies_to` from YAML.
     *
     * @param string $profile_name e.g. "loupe_sites".
     * @return string[]
     */
    public function sites_for_profile($profile_name) {
        $out = array();
        foreach ($this->get_all_sites() as $site_id => $site) {
            if (empty($site['content_profile'])) {
                continue;
            }
            if ($this->profile_name_from_ref($site['content_profile']) === $profile_name) {
                $out[] = $site_id;
            }
        }
        return $out;
    }

    /**
     * Normalise a content_profile reference to its bundle key (basename, no ext).
     *
     * Accepts "config/content_profiles/loupe_sites.yaml", "loupe_sites.yaml",
     * or "loupe_sites" and returns "loupe_sites".
     *
     * @param string $ref
     * @return string
     */
    private function profile_name_from_ref($ref) {
        $base = basename((string) $ref);
        return preg_replace('/\.(ya?ml)$/i', '', $base);
    }

    /**
     * Resolve a site's URL-structure block from `url_structures.yaml`.
     *
     * A site either has its own key under `url_structures.sites` (e.g.
     * `ringspo`) or is covered by a template family via `_applies_to`
     * (e.g. `modernjeweler` → `loupe_sites`). This honours both, so callers
     * never special-case template families.
     *
     * @param string $site_id
     * @return array|null The structure block (level_1.. type_*, *_format), or null.
     */
    public function get_url_structure($site_id) {
        $structures = $this->get_url_structures();
        $sites = isset($structures['sites']) && is_array($structures['sites'])
            ? $structures['sites']
            : array();

        if (isset($sites[$site_id]) && is_array($sites[$site_id])) {
            return $sites[$site_id];
        }

        foreach ($sites as $entry) {
            if (!is_array($entry) || empty($entry['_applies_to']) || !is_array($entry['_applies_to'])) {
                continue;
            }
            if (in_array($site_id, $entry['_applies_to'], true)) {
                return $entry;
            }
        }

        return null;
    }

    /**
     * Resolve the page layout for a (site, page_level, country) tuple.
     *
     * Reads the content profile's `page_structure` block for the level and
     * returns its `hero_component`, `sections`, and `ad_slots`. The renderer
     * iterates this list instead of assuming a fixed sequence, so per-site
     * layout differences (and future archetypes) are honoured from config.
     *
     * Per-country override: if the level block carries a
     * `country_overrides.{country}` map, its keys shallow-override the base
     * (mirrors the `country_in_content.country_overrides` pattern). This is the
     * hook for "guidance on Ringspo US first, then UK/SG" — the section list for
     * a country can diverge without touching PHP.
     *
     * Always returns a well-formed array (empty lists when nothing is defined),
     * and ignores `country_overrides` itself as a presentational key.
     *
     * @param string      $site_id
     * @param string      $page_level   Hyphenated level (shape, all-shapes, ...).
     * @param string|null $country_code Lowercase country code, or null.
     * @return array{hero_component: string|null, sections: string[], ad_slots: string[]}
     */
    public function get_page_layout($site_id, $page_level, $country_code = null) {
        $profile = $this->get_content_profile($site_id);
        $structure = is_array($profile) && isset($profile['page_structure']) && is_array($profile['page_structure'])
            ? $profile['page_structure']
            : array();

        $key = isset(self::PAGE_LEVEL_TO_STRUCTURE_KEY[$page_level])
            ? self::PAGE_LEVEL_TO_STRUCTURE_KEY[$page_level]
            : $page_level;

        $block = isset($structure[$key]) && is_array($structure[$key]) ? $structure[$key] : array();

        if ($country_code !== null
            && isset($block['country_overrides'][$country_code])
            && is_array($block['country_overrides'][$country_code])
        ) {
            $block = array_merge($block, $block['country_overrides'][$country_code]);
        }

        return array(
            'hero_component' => isset($block['hero_component']) && is_string($block['hero_component'])
                ? $block['hero_component']
                : null,
            'sections' => isset($block['sections']) && is_array($block['sections'])
                ? array_values($block['sections'])
                : array(),
            // Section id => band name. Declared per section so a profile's visual
            // rhythm survives inserting or reordering modules; sections absent
            // from the map render as plain bands.
            'section_bands' => isset($block['section_bands']) && is_array($block['section_bands'])
                ? $block['section_bands']
                : array(),
            'ad_slots' => isset($block['ad_slots']) && is_array($block['ad_slots'])
                ? array_values($block['ad_slots'])
                : array(),
        );
    }

    /**
     * ISO currency code for a site's country (from the site config `countries`
     * list), or null when unknown. Used by the renderer to format prices.
     *
     * @param string $site_id
     * @param string $country_code
     * @return string|null
     */
    public function get_currency($site_id, $country_code) {
        $entry = $this->get_country_entry($site_id, $country_code);
        if ($entry === null || empty($entry['currency'])) {
            return null;
        }
        return (string) $entry['currency'];
    }

    /**
     * Navigation declaration for a site, or null when it declares none.
     *
     * Already flat: `_extends` was resolved and the declaration validated at bundle
     * build time by `shared/config/navigation.py`, so there is no inheritance to
     * apply here and an invalid menu never reaches the plugin.
     *
     * @param string $site_id
     * @return array|null
     */
    public function get_navigation($site_id) {
        $bundle = $this->get_bundle();
        $navigation = isset($bundle['navigation']) && is_array($bundle['navigation'])
            ? $bundle['navigation']
            : array();
        if (isset($navigation[$site_id]) && is_array($navigation[$site_id])) {
            return $navigation[$site_id];
        }
        return null;
    }

    /**
     * Resolved navigation wording for one site and locale.
     *
     * Built from `i18n/{locale}/common.json` by the bundle builder, so the menu
     * word is the page word and PHP never parses the i18n tree at request time.
     * Returns `array('label' => …, 'country' => …)`, either key possibly absent
     * when that locale carries none of those terms.
     *
     * @param string $site_id
     * @param string $locale
     * @return array<string, array<string, string>>
     */
    public function get_nav_terms($site_id, $locale) {
        $bundle = $this->get_bundle();
        if (empty($bundle['nav_terms'][$site_id]) || !is_array($bundle['nav_terms'][$site_id])) {
            return array();
        }
        $per_site = $bundle['nav_terms'][$site_id];
        $locale = (string) $locale;

        return (isset($per_site[$locale]) && is_array($per_site[$locale]))
            ? $per_site[$locale]
            : array();
    }

    /**
     * Country config row from the site bundle (locale, currency, table_prefix, …).
     *
     * @param string $site_id
     * @param string $country_code
     * @return array<string, mixed>|null
     */
    public function get_country_entry($site_id, $country_code) {
        $site = $this->get_site($site_id);
        $code = strtolower((string) $country_code);
        if (!is_array($site) || empty($site['countries']) || !is_array($site['countries'])) {
            return null;
        }
        foreach ($site['countries'] as $entry) {
            if (is_array($entry) && isset($entry['code']) && (string) $entry['code'] === $code) {
                return $entry;
            }
        }
        return null;
    }

    /**
     * BCP-47 locale for a site's country (e.g. fr-FR), or null when unknown.
     *
     * @param string $site_id
     * @param string $country_code
     * @return string|null
     */
    public function get_locale($site_id, $country_code) {
        $entry = $this->get_country_entry($site_id, $country_code);
        if ($entry === null || empty($entry['locale'])) {
            return null;
        }
        return (string) $entry['locale'];
    }

    /**
     * Whether Phase 8 consumer features are globally live (launch_sequence flag).
     *
     * Mirrors shared/config/country_markets.py::consumer_features_live().
     *
     * @return bool
     */
    public function consumer_features_live() {
        $bundle = $this->get_bundle();
        $launch = isset($bundle['launch_sequence']) && is_array($bundle['launch_sequence'])
            ? $bundle['launch_sequence']
            : array();
        return !empty($launch['consumer_features_live']);
    }

    /**
     * Site × country consumer-advisory policy from entitlements (ignores go-live flag).
     *
     * @param string $site_id
     * @param string $country_code
     * @return bool
     */
    public function consumer_advisory_policy_enabled($site_id, $country_code) {
        $bundle = $this->get_bundle();
        $ent = isset($bundle['entitlements']) && is_array($bundle['entitlements'])
            ? $bundle['entitlements']
            : array();
        $sites = isset($ent['sites']) && is_array($ent['sites']) ? $ent['sites'] : array();
        if (!isset($sites[$site_id]) || !is_array($sites[$site_id])) {
            return false;
        }
        $site_ent = $sites[$site_id];
        $profile_name = isset($site_ent['consumer_advisory']['profile'])
            ? (string) $site_ent['consumer_advisory']['profile']
            : 'none';
        $profiles = isset($ent['consumer_advisory_profiles']) && is_array($ent['consumer_advisory_profiles'])
            ? $ent['consumer_advisory_profiles']
            : array();
        if (!isset($profiles[$profile_name]['countries']) || !is_array($profiles[$profile_name]['countries'])) {
            return false;
        }
        $countries = $profiles[$profile_name]['countries'];
        $code = strtolower((string) $country_code);
        if (!isset($countries[$code])) {
            return false;
        }
        $entry = $countries[$code];
        if ($entry === true) {
            return true;
        }
        if (is_array($entry)) {
            return !isset($entry['enabled']) || $entry['enabled'] !== false;
        }
        return false;
    }

    /**
     * Whether consumer advisory may render for site × country (policy + go-live).
     *
     * @param string $site_id
     * @param string $country_code
     * @return bool
     */
    public function consumer_advisory_enabled($site_id, $country_code) {
        return $this->consumer_features_live()
            && $this->consumer_advisory_policy_enabled($site_id, $country_code);
    }

    // =========================================================================
    // Shape slug (mirrors shared.utils.shape_to_s3_slug)
    // =========================================================================

    /**
     * Convert a shape name to its S3 folder slug.
     *
     * Mirrors shared/utils.py shape_to_s3_slug(): applies SHAPE_S3_SLUG_MAP for
     * shapes needing a '-cut' suffix; otherwise lowercases and replaces spaces
     * with dashes.
     *
     * @param string $shape Raw shape name (e.g. 'Asscher', 'round').
     * @return string Lowercase S3-safe slug (e.g. 'asscher-cut', 'round').
     */
    public function shape_to_s3_slug($shape) {
        $key = strtolower(trim((string) $shape));
        if (isset(self::SHAPE_S3_SLUG_MAP[$key])) {
            return self::SHAPE_S3_SLUG_MAP[$key];
        }
        return str_replace(' ', '-', $key);
    }

    /**
     * Public URL shape slug for a site (price and size paths).
     *
     * This is not the S3 folder slug. Ringspo prices live at `/…/cushion/`;
     * S3 objects live under `cushion-cut/`.
     *
     * @param string      $shape   Canonical shape name (e.g. 'cushion').
     * @param string      $site_id
     * @param string|null $country When set, prefer that country's localised slug.
     * @return string
     */
    public function shape_to_url_slug($shape, $site_id, $country = null) {
        $key = strtolower(trim((string) $shape));
        if ($key === '') {
            return '';
        }
        if ($country !== null && $country !== '') {
            $segments = $this->url_locale_segments($site_id, $country);
            $shapes = isset($segments['shapes']) && is_array($segments['shapes'])
                ? $segments['shapes']
                : array();
            foreach ($shapes as $loc_slug => $canonical) {
                if (strtolower((string) $canonical) === $key) {
                    return (string) $loc_slug;
                }
            }
        }
        $structures = $this->get_url_structures();
        $variations = isset($structures['shape_variations'][$key])
            && is_array($structures['shape_variations'][$key])
            ? $structures['shape_variations'][$key]
            : array();
        $slug = isset($variations[$site_id]) && (string) $variations[$site_id] !== ''
            ? (string) $variations[$site_id]
            : $key;
        if (function_exists('sanitize_title')) {
            return sanitize_title($slug);
        }
        return str_replace(' ', '-', strtolower($slug));
    }

    /**
     * Resolve a URL shape slug back to the canonical KB shape name for a site.
     *
     * @param string      $slug    URL segment (e.g. 'round', 'oval', 'kissenschliff').
     * @param string      $site_id
     * @param string|null $country When set, try that country's localised slug map first.
     * @return string|null
     */
    public function slug_to_shape($slug, $site_id, $country = null) {
        $slug = strtolower(trim((string) $slug));
        if ($slug === '') {
            return null;
        }
        if ($country !== null && $country !== '') {
            $segments = $this->url_locale_segments($site_id, $country);
            $shapes = isset($segments['shapes']) && is_array($segments['shapes'])
                ? $segments['shapes']
                : array();
            foreach ($shapes as $loc_slug => $canonical) {
                if (strtolower((string) $loc_slug) === $slug) {
                    return (string) $canonical;
                }
            }
        }
        $structures = $this->get_url_structures();
        $variations = isset($structures['shape_variations']) && is_array($structures['shape_variations'])
            ? $structures['shape_variations']
            : array();
        foreach ($variations as $shape => $per_site) {
            if (!is_array($per_site)) {
                continue;
            }
            if (isset($per_site[$site_id]) && strtolower((string) $per_site[$site_id]) === $slug) {
                return (string) $shape;
            }
        }
        $legacy = isset($structures['shape_slug_mappings']) && is_array($structures['shape_slug_mappings'])
            ? $structures['shape_slug_mappings']
            : array();
        foreach ($legacy as $shape => $per_site) {
            if (!is_array($per_site)) {
                continue;
            }
            if (isset($per_site[$site_id]) && strtolower((string) $per_site[$site_id]) === $slug) {
                return (string) $shape;
            }
        }
        return str_replace('-', ' ', $slug);
    }

    /**
     * Resolve a size-module URL segment back to the canonical KB shape name.
     *
     * Size pages are published under the S3 folder slug, not the site's price
     * shape slug: LDN_Size_Renderer::build_size_shape_hub_url() and friends all
     * build paths with shape_to_s3_slug(), so Ringspo's cushion hub lives at
     * `/diamond-size/cushion-cut/` while its price pages use `/…/cushion/`.
     * The S3 map therefore has to be tried before the per-site slug map.
     *
     * Without this the slug falls through slug_to_shape()'s dash-to-space
     * fallback and yields the non-shape string 'cushion cut', which matches no
     * key in the size-checker manifest (so the scale explorer silently dies)
     * and no entry in the test-combos allowlist.
     *
     * @param string $slug    URL segment (e.g. 'cushion-cut', 'round').
     * @param string $site_id
     * @return string|null Canonical shape name (e.g. 'cushion') or null.
     */
    public function size_slug_to_shape($slug, $site_id) {
        $slug = strtolower(trim((string) $slug));
        if ($slug === '') {
            return null;
        }
        foreach (self::SHAPE_S3_SLUG_MAP as $shape => $s3_slug) {
            if ($s3_slug === $slug) {
                return $shape;
            }
        }
        return $this->slug_to_shape($slug, $site_id);
    }

    /**
     * Country code that gates the size module in rollout (US-only at launch).
     *
     * @param string $site_id
     * @return string
     */
    public function size_rollout_country($site_id) {
        $site = $this->get_site($site_id);
        if (is_array($site)
            && isset($site['size_module']['rollout_country'])
            && is_string($site['size_module']['rollout_country'])
        ) {
            return strtolower(trim($site['size_module']['rollout_country']));
        }
        return 'us';
    }

    /**
     * Legacy WP ring-guide inject config from the site's content profile.
     *
     * @param string $site_id
     * @return array|null Null when the profile omits the block or it is disabled.
     */
    public function editorial_ring_guides($site_id) {
        $profile = $this->get_content_profile($site_id);
        if ($profile === null
            || empty($profile['editorial_ring_guides'])
            || !is_array($profile['editorial_ring_guides'])
        ) {
            return null;
        }
        $guides = $profile['editorial_ring_guides'];
        if (empty($guides['enabled'])) {
            return null;
        }
        return $guides;
    }

    /**
     * Whether US pricing pages should link to the size tree (Decision 5).
     *
     * @param string $site_id
     * @return bool
     */
    public function size_price_internal_links($site_id) {
        $site = $this->get_site($site_id);
        if (!is_array($site) || !isset($site['size_module']) || !is_array($site['size_module'])) {
            return false;
        }
        return !empty($site['size_module']['price_internal_links']);
    }

    /**
     * Size URL tree layout: shape_first (Ringspo) or carat_first (Diamond Chart).
     *
     * @param string $site_id
     * @return string
     */
    public function size_url_layout($site_id) {
        $site = $this->get_site($site_id);
        if (is_array($site)
            && isset($site['size_module']['url_layout'])
            && is_string($site['size_module']['url_layout'])
        ) {
            $layout = strtolower(trim($site['size_module']['url_layout']));
            if ($layout === 'carat_first' || $layout === 'shape_first') {
                return $layout;
            }
        }
        return 'shape_first';
    }

    /**
     * Whether the site serves a marketing shell at WordPress front page (/).
     *
     * @param string $site_id
     * @return bool
     */
    public function size_marketing_home($site_id) {
        $site = $this->get_site($site_id);
        return is_array($site)
            && isset($site['size_module'])
            && is_array($site['size_module'])
            && !empty($site['size_module']['marketing_home']);
    }

    // =========================================================================
    // Internal
    // =========================================================================

    /**
     * Log a config-layer message (errors/warnings only — no per-request noise).
     *
     * @param string $message
     * @return void
     */
    private function log($message) {
        LDN_Plugin::debug_log('Config', $message);
    }
}
