<?php
/**
 * Config reader.
 *
 * Single source of truth for site/profile/URL config inside the plugin. It does
 * NOT parse YAML at runtime (anti-pattern per PRD-005 CP51). Instead it loads a
 * deployed JSON **config bundle** — the serialised form of the same files the
 * Python pipeline reads:
 *
 *   - config/sites/*.yaml
 *   - config/content_profiles/*.yaml
 *   - config/url_structures.yaml
 *   - config/site_content_entitlements.yaml
 *   - config/artefacts.yaml
 *   - config/staging_qa_matrix.yaml
 *   - config/network_consumer.yaml
 *
 * The bundle is generated by a build step (separate checkpoint) and deployed
 * with the plugin. This keeps the plugin's source of truth identical to the
 * pipeline while avoiding a YAML parser dependency and per-request parsing.
 *
 * Expected bundle shape (JSON):
 * {
 *   "version": "2026-06-16T01:00:00Z" | "<git-sha>",
 *   "generated_at": "<iso8601>",
 *   "sites":            { "<site_id>": { ...site config... }, ... },
 *   "content_profiles": { "<profile_name>": { ...profile... }, ... },
 *   "url_structures":   { ... },
 *   "entitlements":     { ... },
 *   "artefacts":        { ... }
 * }
 *
 * `content_profiles` is keyed by profile NAME (the YAML basename without
 * extension, e.g. "loupe_sites", "ringspo"); each site config's
 * `content_profile` value (a path like
 * "config/content_profiles/loupe_sites.yaml") resolves to that key.
 *
 * @package LoupeDiamondNetwork
 * @since   0.1.0
 */

if (!defined('ABSPATH')) {
    exit;
}

final class LDN_Config {

    /**
     * Transient key for the parsed bundle.
     */
    const TRANSIENT_KEY = 'ldn_config_bundle';

    /**
     * Transient TTL (seconds). Bundle changes only on deploy, so this can be
     * long; it is also invalidated whenever the bundle file mtime changes.
     */
    const TRANSIENT_TTL = 12 * HOUR_IN_SECONDS;

    /**
     * Canonical shape -> S3 slug map. Mirrors shared/utils.py SHAPE_S3_SLUG_MAP
     * exactly. Keys are lowercased shape names.
     *
     * @var array<string, string>
     */
    const SHAPE_S3_SLUG_MAP = array(
        'asscher'           => 'asscher-cut',
        'cushion'           => 'cushion-cut',
        'cushion elongated' => 'cushion-cut',
        'emerald'           => 'emerald-cut',
        'princess'          => 'princess-cut',
    );

    /**
     * Page level (hyphenated, S3/entitlement form) → `page_structure` key
     * (underscored, content-profile form). Mirrors the dual naming noted in
     * site_content_entitlements.yaml.
     *
     * @var array<string, string>
     */
    const PAGE_LEVEL_TO_STRUCTURE_KEY = array(
        'shape'        => 'individual_shape',
        'all-shapes'   => 'all_shapes',
        'diamond-type' => 'diamond_type',
        'top-level'    => 'top_level',
    );

    /**
     * Singleton instance.
     *
     * @var LDN_Config|null
     */
    private static $instance = null;

    /**
     * In-memory copy of the parsed bundle for this request.
     *
     * @var array|null
     */
    private $bundle = null;

    /**
     * Get the singleton instance.
     *
     * @return LDN_Config
     */
    public static function instance() {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * Private constructor for singleton.
     */
    private function __construct() {}

    // =========================================================================
    // Bundle loading
    // =========================================================================

    /**
     * Absolute path to the deployed config bundle.
     *
     * Filterable so deployments can point at a shared location outside the
     * plugin directory.
     *
     * @return string
     */
    public function bundle_path() {
        $default = LDN_PLUGIN_DIR . 'data/config-bundle.json';
        return (string) apply_filters('ldn_config_bundle_path', $default);
    }

    /**
     * Load and cache the config bundle.
     *
     * Returns an empty (but well-formed) structure if the bundle is missing or
     * invalid, logging the reason. Callers can always rely on the top-level
     * keys existing.
     *
     * @return array
     */
    public function get_bundle() {
        if ($this->bundle !== null) {
            return $this->bundle;
        }

        $path = $this->bundle_path();
        $mtime = is_readable($path) ? (int) @filemtime($path) : 0;

        $cached = get_transient(self::TRANSIENT_KEY);
        if (is_array($cached) && isset($cached['_mtime']) && $cached['_mtime'] === $mtime && $mtime > 0) {
            $this->bundle = $cached;
            return $this->bundle;
        }

        $this->bundle = $this->read_bundle_file($path, $mtime);
        set_transient(self::TRANSIENT_KEY, $this->bundle, self::TRANSIENT_TTL);

        return $this->bundle;
    }

    /**
     * Read and decode the bundle file from disk.
     *
     * @param string $path  Absolute path to the bundle.
     * @param int    $mtime File mtime (stamped into the result for cache keying).
     * @return array
     */
    private function read_bundle_file($path, $mtime) {
        $empty = $this->empty_bundle($mtime);

        if (!is_readable($path)) {
            $this->log("config bundle not found at {$path}; using empty config");
            return $empty;
        }

        $raw = file_get_contents($path);
        if ($raw === false || $raw === '') {
            $this->log("config bundle at {$path} is empty or unreadable");
            return $empty;
        }

        $decoded = json_decode($raw, true);
        if (!is_array($decoded)) {
            $this->log("config bundle at {$path} is not valid JSON: " . json_last_error_msg());
            return $empty;
        }

        return array_merge($empty, $decoded, array('_mtime' => $mtime));
    }

    /**
     * Well-formed empty bundle so accessors never hit undefined keys.
     *
     * @param int $mtime
     * @return array
     */
    private function empty_bundle($mtime = 0) {
        return array(
            '_mtime'           => $mtime,
            'version'          => null,
            'generated_at'     => null,
            'sites'            => array(),
            'content_profiles' => array(),
            'url_structures'   => array(),
            'entitlements'     => array(),
            'artefacts'        => array(),
            'network_consumer' => array(),
        );
    }

    /**
     * Clear cached config (call on deploy / bundle refresh).
     *
     * @return void
     */
    public function flush() {
        $this->bundle = null;
        delete_transient(self::TRANSIENT_KEY);
    }

    // =========================================================================
    // Site accessors
    // =========================================================================

    /**
     * All site configs, indexed by site_id.
     *
     * @return array<string, array>
     */
    public function get_all_sites() {
        $bundle = $this->get_bundle();
        return is_array($bundle['sites']) ? $bundle['sites'] : array();
    }

    /**
     * One site config by site_id.
     *
     * @param string $site_id
     * @return array|null Null when unknown.
     */
    public function get_site($site_id) {
        $sites = $this->get_all_sites();
        return isset($sites[$site_id]) && is_array($sites[$site_id]) ? $sites[$site_id] : null;
    }

    /**
     * Raw url_structures bundle section.
     *
     * @return array
     */
    public function get_url_structures() {
        $bundle = $this->get_bundle();
        return is_array($bundle['url_structures']) ? $bundle['url_structures'] : array();
    }

    /**
     * Entitlements bundle section.
     *
     * @return array
     */
    public function get_entitlements() {
        $bundle = $this->get_bundle();
        return is_array($bundle['entitlements']) ? $bundle['entitlements'] : array();
    }

    /**
     * Staging QA matrix (shape combos, preset groups, country cap).
     *
     * @return array
     */
    public function get_staging_qa_matrix() {
        $bundle = $this->get_bundle();
        return isset($bundle['staging_qa_matrix']) && is_array($bundle['staging_qa_matrix'])
            ? $bundle['staging_qa_matrix']
            : array();
    }

    /**
     * Public HTTPS URL for network-rollout.json (from config/network_consumer.yaml).
     *
     * @return string Empty when the bundle omits rollout.url.
     */
    public function get_rollout_url() {
        $bundle = $this->get_bundle();
        $consumer = isset($bundle['network_consumer']) && is_array($bundle['network_consumer'])
            ? $bundle['network_consumer']
            : array();
        $rollout = isset($consumer['rollout']) && is_array($consumer['rollout'])
            ? $consumer['rollout']
            : array();
        $url = isset($rollout['url']) ? trim((string) $rollout['url']) : '';
        return $url;
    }

    /**
     * network_consumer.yaml slice from the bundle.
     *
     * @return array
     */
    public function network_consumer() {
        $bundle = $this->get_bundle();
        return isset($bundle['network_consumer']) && is_array($bundle['network_consumer'])
            ? $bundle['network_consumer']
            : array();
    }

    /**
     * Combined sitemap index path (price + size child sitemaps).
     *
     * @return string
     */
    public function network_sitemap_index_path() {
        $consumer = $this->network_consumer();
        $path = isset($consumer['network_sitemap_index'])
            ? trim((string) $consumer['network_sitemap_index'])
            : '/sitemaps/network.xml';
        return $path !== '' ? $path : '/sitemaps/network.xml';
    }

    /**
     * Price-module XML sitemap path for a site (from url_structures or derived).
     *
     * @param string $site_id
     * @return string|null
     */
    public function price_sitemap_path($site_id) {
        $structure = $this->get_url_structure($site_id);
        if (!is_array($structure)) {
            return null;
        }
        if (!empty($structure['price_level_sitemap'])) {
            return (string) $structure['price_level_sitemap'];
        }
        if (!empty($structure['level_1'])) {
            return rtrim((string) $structure['level_1'], '/') . '/sitemap.xml';
        }
        return '/diamond-prices/sitemap.xml';
    }

    /**
     * Size-module XML sitemap path for a site.
     *
     * @param string $site_id
     * @return string|null
     */
    public function size_sitemap_path($site_id) {
        $structure = $this->get_url_structure($site_id);
        if (!is_array($structure) || empty($structure['size_level_sitemap'])) {
            return null;
        }
        return (string) $structure['size_level_sitemap'];
    }

    // =========================================================================
    // Content profile resolution (mirrors shared.config.profiles.resolve_content_profile)
    // =========================================================================

    /**
     * Resolve a site's content profile.
     *
     * Reads the site config's `content_profile` value (a path or bare name) and
     * returns the matching entry from the bundle's `content_profiles` map.
     * Template profiles (e.g. loupe_sites) are stored once and shared by every
     * site whose `content_profile` points at them.
     *
     * @param string $site_id
     * @return array|null Null when the site or its profile is unknown.
     */
    public function get_content_profile($site_id) {
        $site = $this->get_site($site_id);
        if ($site === null || empty($site['content_profile'])) {
            return null;
        }

        $name = $this->profile_name_from_ref($site['content_profile']);
        $bundle = $this->get_bundle();
        $profiles = is_array($bundle['content_profiles']) ? $bundle['content_profiles'] : array();

        return isset($profiles[$name]) && is_array($profiles[$name]) ? $profiles[$name] : null;
    }

    /**
     * Merged `file_naming` block for a site's content profile.
     *
     * Used by the S3 key resolver (CP51_03) to build artefact filenames without
     * hardcoding. Returns an empty array when the profile defines none.
     *
     * @param string $site_id
     * @return array
     */
    public function get_file_naming($site_id) {
        $profile = $this->get_content_profile($site_id);
        if ($profile === null || empty($profile['file_naming']) || !is_array($profile['file_naming'])) {
            return array();
        }
        return $profile['file_naming'];
    }

    /**
     * Site IDs that resolve to a given content profile name.
     *
     * Inverts the site -> profile mapping so callers can answer "which sites use
     * the loupe_sites template?" without re-reading `_applies_to` from YAML.
     *
     * @param string $profile_name e.g. "loupe_sites".
     * @return string[]
     */
    public function sites_for_profile($profile_name) {
        $out = array();
        foreach ($this->get_all_sites() as $site_id => $site) {
            if (empty($site['content_profile'])) {
                continue;
            }
            if ($this->profile_name_from_ref($site['content_profile']) === $profile_name) {
                $out[] = $site_id;
            }
        }
        return $out;
    }

    /**
     * Normalise a content_profile reference to its bundle key (basename, no ext).
     *
     * Accepts "config/content_profiles/loupe_sites.yaml", "loupe_sites.yaml",
     * or "loupe_sites" and returns "loupe_sites".
     *
     * @param string $ref
     * @return string
     */
    private function profile_name_from_ref($ref) {
        $base = basename((string) $ref);
        return preg_replace('/\.(ya?ml)$/i', '', $base);
    }

    /**
     * Resolve a site's URL-structure block from `url_structures.yaml`.
     *
     * A site either has its own key under `url_structures.sites` (e.g.
     * `ringspo`) or is covered by a template family via `_applies_to`
     * (e.g. `modernjeweler` → `loupe_sites`). This honours both, so callers
     * never special-case template families.
     *
     * @param string $site_id
     * @return array|null The structure block (level_1.. type_*, *_format), or null.
     */
    public function get_url_structure($site_id) {
        $structures = $this->get_url_structures();
        $sites = isset($structures['sites']) && is_array($structures['sites'])
            ? $structures['sites']
            : array();

        if (isset($sites[$site_id]) && is_array($sites[$site_id])) {
            return $sites[$site_id];
        }

        foreach ($sites as $entry) {
            if (!is_array($entry) || empty($entry['_applies_to']) || !is_array($entry['_applies_to'])) {
                continue;
            }
            if (in_array($site_id, $entry['_applies_to'], true)) {
                return $entry;
            }
        }

        return null;
    }

    /**
     * Resolve the page layout for a (site, page_level, country) tuple.
     *
     * Reads the content profile's `page_structure` block for the level and
     * returns its `hero_component`, `sections`, and `ad_slots`. The renderer
     * iterates this list instead of assuming a fixed sequence, so per-site
     * layout differences (and future archetypes) are honoured from config.
     *
     * Per-country override: if the level block carries a
     * `country_overrides.{country}` map, its keys shallow-override the base
     * (mirrors the `country_in_content.country_overrides` pattern). This is the
     * hook for "guidance on Ringspo US first, then UK/SG" — the section list for
     * a country can diverge without touching PHP.
     *
     * Always returns a well-formed array (empty lists when nothing is defined),
     * and ignores `country_overrides` itself as a presentational key.
     *
     * @param string      $site_id
     * @param string      $page_level   Hyphenated level (shape, all-shapes, ...).
     * @param string|null $country_code Lowercase country code, or null.
     * @return array{hero_component: string|null, sections: string[], ad_slots: string[]}
     */
    public function get_page_layout($site_id, $page_level, $country_code = null) {
        $profile = $this->get_content_profile($site_id);
        $structure = is_array($profile) && isset($profile['page_structure']) && is_array($profile['page_structure'])
            ? $profile['page_structure']
            : array();

        $key = isset(self::PAGE_LEVEL_TO_STRUCTURE_KEY[$page_level])
            ? self::PAGE_LEVEL_TO_STRUCTURE_KEY[$page_level]
            : $page_level;

        $block = isset($structure[$key]) && is_array($structure[$key]) ? $structure[$key] : array();

        if ($country_code !== null
            && isset($block['country_overrides'][$country_code])
            && is_array($block['country_overrides'][$country_code])
        ) {
            $block = array_merge($block, $block['country_overrides'][$country_code]);
        }

        return array(
            'hero_component' => isset($block['hero_component']) && is_string($block['hero_component'])
                ? $block['hero_component']
                : null,
            'sections' => isset($block['sections']) && is_array($block['sections'])
                ? array_values($block['sections'])
                : array(),
            'ad_slots' => isset($block['ad_slots']) && is_array($block['ad_slots'])
                ? array_values($block['ad_slots'])
                : array(),
        );
    }

    /**
     * ISO currency code for a site's country (from the site config `countries`
     * list), or null when unknown. Used by the renderer to format prices.
     *
     * @param string $site_id
     * @param string $country_code
     * @return string|null
     */
    public function get_currency($site_id, $country_code) {
        $site = $this->get_site($site_id);
        if (!is_array($site) || empty($site['countries']) || !is_array($site['countries'])) {
            return null;
        }
        foreach ($site['countries'] as $entry) {
            if (is_array($entry) && isset($entry['code']) && $entry['code'] === $country_code) {
                return isset($entry['currency']) ? (string) $entry['currency'] : null;
            }
        }
        return null;
    }

    // =========================================================================
    // Shape slug (mirrors shared.utils.shape_to_s3_slug)
    // =========================================================================

    /**
     * Convert a shape name to its S3 folder slug.
     *
     * Mirrors shared/utils.py shape_to_s3_slug(): applies SHAPE_S3_SLUG_MAP for
     * shapes needing a '-cut' suffix; otherwise lowercases and replaces spaces
     * with dashes.
     *
     * @param string $shape Raw shape name (e.g. 'Asscher', 'round').
     * @return string Lowercase S3-safe slug (e.g. 'asscher-cut', 'round').
     */
    public function shape_to_s3_slug($shape) {
        $key = strtolower(trim((string) $shape));
        if (isset(self::SHAPE_S3_SLUG_MAP[$key])) {
            return self::SHAPE_S3_SLUG_MAP[$key];
        }
        return str_replace(' ', '-', $key);
    }

    /**
     * Resolve a URL shape slug back to the canonical KB shape name for a site.
     *
     * @param string $slug    URL segment (e.g. 'round', 'oval').
     * @param string $site_id
     * @return string|null
     */
    public function slug_to_shape($slug, $site_id) {
        $slug = strtolower(trim((string) $slug));
        if ($slug === '') {
            return null;
        }
        $bundle = $this->get_bundle();
        $mappings = isset($bundle['url_structures']['shape_slug_mappings'])
            && is_array($bundle['url_structures']['shape_slug_mappings'])
            ? $bundle['url_structures']['shape_slug_mappings']
            : array();
        foreach ($mappings as $shape => $per_site) {
            if (!is_array($per_site)) {
                continue;
            }
            if (isset($per_site[$site_id]) && strtolower((string) $per_site[$site_id]) === $slug) {
                return (string) $shape;
            }
        }
        return str_replace('-', ' ', $slug);
    }

    /**
     * Country code that gates the size module in rollout (US-only at launch).
     *
     * @param string $site_id
     * @return string
     */
    public function size_rollout_country($site_id) {
        $site = $this->get_site($site_id);
        if (is_array($site)
            && isset($site['size_module']['rollout_country'])
            && is_string($site['size_module']['rollout_country'])
        ) {
            return strtolower(trim($site['size_module']['rollout_country']));
        }
        return 'us';
    }

    /**
     * Whether US pricing pages should link to the size tree (Decision 5).
     *
     * @param string $site_id
     * @return bool
     */
    public function size_price_internal_links($site_id) {
        $site = $this->get_site($site_id);
        if (!is_array($site) || !isset($site['size_module']) || !is_array($site['size_module'])) {
            return false;
        }
        return !empty($site['size_module']['price_internal_links']);
    }

    /**
     * Size URL tree layout: shape_first (Ringspo) or carat_first (Diamond Chart).
     *
     * @param string $site_id
     * @return string
     */
    public function size_url_layout($site_id) {
        $site = $this->get_site($site_id);
        if (is_array($site)
            && isset($site['size_module']['url_layout'])
            && is_string($site['size_module']['url_layout'])
        ) {
            $layout = strtolower(trim($site['size_module']['url_layout']));
            if ($layout === 'carat_first' || $layout === 'shape_first') {
                return $layout;
            }
        }
        return 'shape_first';
    }

    /**
     * Whether the site serves a marketing shell at WordPress front page (/).
     *
     * @param string $site_id
     * @return bool
     */
    public function size_marketing_home($site_id) {
        $site = $this->get_site($site_id);
        return is_array($site)
            && isset($site['size_module'])
            && is_array($site['size_module'])
            && !empty($site['size_module']['marketing_home']);
    }

    // =========================================================================
    // Internal
    // =========================================================================

    /**
     * Log a config-layer message (errors/warnings only — no per-request noise).
     *
     * @param string $message
     * @return void
     */
    private function log($message) {
        LDN_Plugin::debug_log('Config', $message);
    }
}
